'use strict';
const $ = id => document.getElementById(id);
const state = {token: '', scan: null, selected: new Set(), keepers: {}, kept: new Set(), filter: 'all', plan: null, job: null, compare: null, busy: false};
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const name = path => path.split(/[\\/]/).pop();
function bytes(value) { if (!value) return '0 B'; const n=Math.min(4,Math.floor(Math.log(value)/Math.log(1024)));return (value/1024**n).toFixed(n?1:0)+' '+['B','KB','MB','GB','TB'][n]; }
async function api(route, data={}) { const response = await fetch('/api/'+route,{method:'POST',headers:{'Content-Type':'application/json','X-Katharo-Token':state.token},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw new Error(result.error||'Request failed.');return result; }
function notice(message) { $('notice').hidden=!message;$('notice').textContent=message; }
function chosen() { return state.scan ? state.scan.files.filter(f=>state.selected.has(f.id)) : []; }
function renderSelection() {const files=chosen(),size=files.reduce((n,f)=>n+f.size,0);$('metric-selected').textContent=bytes(size);$('metric-count').textContent=files.length+' files selected';$('space-value').textContent=bytes(size);$('selection-summary').textContent=files.length?files.length+' extra copies · '+bytes(size):'Nothing selected yet.';$('prepare-open').disabled=!files.length||state.busy;}
function renderGroups() {if(!state.scan)return;const groups=state.scan.groups.filter(g=>state.filter==='all'||(state.filter==='exact'?g.kind==='exact':g.kind!=='exact'));$('groups').innerHTML=groups.length?groups.map(g=>{const keeper=state.keepers[g.id]||g.files[0].id,kept=state.kept.has(g.id),exact=g.kind==='exact';return `<article class="group" data-group="${esc(g.id)}"><div class="group-head"><div><h3>${esc(name(g.files[0].path))}</h3><div class="evidence">${esc(g.evidence)}</div></div><span class="pill ${exact?'exact-badge':'doc-badge'}">${exact?'Exact duplicate':g.kind==='content'?'Matching text':'Possible revision'}</span></div>${g.warning?`<p class="warning-text">${esc(g.warning)}</p>`:''}${g.files.map(f=>`<div class="file"><label><input type="checkbox" data-select="${f.id}" ${state.selected.has(f.id)?'checked':''} ${!exact||f.id===keeper||kept?'disabled':''} aria-label="Select ${esc(name(f.path))} for quarantine"><span><span class="name">${esc(name(f.path))}</span><span class="path">${esc(f.path)} · ${bytes(f.size)}</span></span></label>${kept?'<span class="keeper">Keep · reviewed</span>':exact&&f.id===keeper?'<span class="keeper">✓ Retained copy</span>':exact?`<button class="text-button" data-keeper="${f.id}">Keep this copy</button>`:'<span class="keeper">Keep pending review</span>'}</div>`).join('')}<div class="group-actions">${exact?`<button class="text-button" data-extras="${esc(g.id)}" ${kept?'disabled':''}>Select extra copies →</button>`:`<button class="text-button" data-compare="${esc(g.id)}">Compare extracted text →</button>`}<button class="text-button" data-keep="${esc(g.id)}">${kept?'Reopen decision':exact?'Keep all copies':'Keep both · different purpose'}</button></div></article>`}).join(''):'<div class="empty">No matching groups in this view.</div>';renderSelection();}
function renderScan() {const s=state.scan;$('results').hidden=false;$('metric-size').textContent=bytes(s.total_bytes);$('metric-files').textContent=s.file_count.toLocaleString()+' files inventoried';$('metric-extra').textContent=bytes(s.recoverable||0);$('metric-groups').textContent=s.groups.filter(g=>g.kind==='exact').length+' exact groups';$('metric-docs').textContent=s.groups.filter(g=>g.kind!=='exact').length+' groups';$('scan-status').textContent='Scan complete · '+s.root;const types=Object.entries(s.by_type).sort((a,b)=>b[1]-a[1]).slice(0,5),max=Math.max(1,...types.map(x=>x[1]));$('type-chart').innerHTML=types.map(([type,size])=>`<div class="chart-row"><span>${esc(type.toUpperCase())}</span><div class="chart-track"><span data-width="${size/max*100}"></span></div><em>${bytes(size)}</em></div>`).join('');document.querySelectorAll('[data-width]').forEach(el=>{el.style.width=el.dataset.width+'%';});$('warnings').hidden=!s.warnings.length;$('warning-count').textContent=s.warnings.length+' scan notes / skipped items';$('warning-list').innerHTML=s.warnings.slice(0,200).map(w=>`<p>${esc(w.path)}<br>${esc(w.reason)}</p>`).join('');renderGroups();}
async function poll() {if(!state.job)return;try{const job=await api('job',{id:state.job});$('progress-label').textContent=job.phase+' · '+job.count.toLocaleString()+' processed';if(job.status==='running'){setTimeout(poll,650);return;}state.job=null;state.busy=false;$('scan').disabled=false;$('cancel').hidden=true;$('progress').hidden=true;if(job.status==='complete'){state.scan=await api('scan-result',{id:job.scan_id});state.selected.clear();state.keepers={};state.kept.clear();renderScan();notice('Scan complete. Review the evidence before selecting extra copies.');}else notice(job.status==='cancelled'?'Scan cancelled. No files were moved.':job.error||'Scan failed.');}catch(e){notice(e.message);state.busy=false;state.job=null;$('scan').disabled=false;$('cancel').hidden=true;$('progress').hidden=true;}}
async function history() {$('workspace').hidden=true;$('history').hidden=false;$('nav-workspace').classList.remove('active');$('nav-history').classList.add('active');try{const plans=await api('history');$('history-list').innerHTML=plans.length?plans.map(p=>`<article class="history-card"><div class="group-head"><h3>${bytes(p.bytes)} · ${p.items.length} selected files</h3><span class="pill">${esc(p.status)}</span></div><p class="status">${esc(p.destination)} · ${new Date(p.created*1000).toLocaleString()}</p>${p.items.map(i=>`<div class="history-item">${esc(name(i.file.path))} <span class="pill">${esc(i.status)}</span><div class="path">Original: ${esc(i.file.path)}</div>${i.error?`<p class="warning-text">${esc(i.error)}</p>`:''}</div>`).join('')}${p.items.some(i=>['quarantined','moving','restoring'].includes(i.status))?`<button class="secondary" data-restore="${p.id}">Restore available files</button>`:''}${['executing','partial'].includes(p.status)?'<p class="warning-text">Review each outcome. Interrupted moves may require manual reconciliation with the manifest.</p>':''}</article>`).join(''):'<div class="empty">No quarantine history yet. Your approved plans will appear here.</div>';}catch(e){notice(e.message);}}
function invalidatePlan() {state.plan=null;$('validated').hidden=true;$('consent').checked=false;$('execute').disabled=true;}
$('browse').onclick=async()=>{try{$('browse').disabled=true;const r=await api('pick-folder');if(r.folder)$('folder').value=r.folder;}catch(e){notice(e.message);}finally{$('browse').disabled=false;}};
$('scan').onclick=async()=>{try{state.busy=true;$('scan').disabled=true;$('cancel').hidden=false;$('progress').hidden=false;notice('');const job=await api('scan',{folder:$('folder').value,recursive:$('recursive').checked,documents:$('documents').checked});state.job=job.id;poll();}catch(e){notice(e.message);state.busy=false;$('scan').disabled=false;$('cancel').hidden=true;$('progress').hidden=true;}};
$('cancel').onclick=()=>api('cancel',{id:state.job}).catch(e=>notice(e.message));
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));renderGroups();});
$('groups').addEventListener('change',e=>{const id=e.target.dataset.select;if(!id)return;if(e.target.checked)state.selected.add(id);else state.selected.delete(id);renderSelection();});
$('groups').addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;const g=state.scan.groups.find(x=>x.id===b.closest('[data-group]').dataset.group);if(b.dataset.keeper){state.keepers[g.id]=b.dataset.keeper;state.selected.delete(b.dataset.keeper);renderGroups();}if(b.dataset.extras){const keeper=state.keepers[g.id]||g.files[0].id;g.files.filter(f=>f.id!==keeper).forEach(f=>state.selected.add(f.id));renderGroups();}if(b.dataset.keep){const reopen=state.kept.has(g.id);if(reopen)state.kept.delete(g.id);else{state.kept.add(g.id);g.files.forEach(f=>state.selected.delete(f.id));}renderGroups();try{await api('decision',{scan_id:state.scan.id,group_id:g.id,decision:reopen?'reopen':'keep-all'});}catch(err){notice(err.message);}}if(b.dataset.compare){state.compare=g;$('compare-evidence').textContent=g.evidence;$('compare-texts').innerHTML=g.files.map((f,i)=>`<section><h3>${esc(name(f.path))}</h3><pre>${esc(g.texts[i])}</pre></section>`).join('');$('compare-dialog').showModal();}});
$('prepare-open').onclick=()=>{invalidatePlan();$('plan-error').textContent='';$('plan-files').innerHTML=chosen().map(f=>{const g=state.scan.groups.find(x=>x.kind==='exact'&&x.files.some(y=>y.id===f.id));const keep=g.files.filter(x=>!state.selected.has(x.id));return `<div class="plan-file">${esc(name(f.path))} · ${bytes(f.size)}<div class="path">Move: ${esc(f.path)}<br>Retain: ${keep.map(x=>esc(x.path)).join(' · ')}</div></div>`}).join('');$('plan-dialog').showModal();};
$('close-plan').onclick=()=>{if(!state.busy)$('plan-dialog').close();};$('plan-dialog').addEventListener('cancel',e=>{if(state.busy)e.preventDefault();});$('destination').oninput=invalidatePlan;
$('pick-destination').onclick=async()=>{try{const r=await api('pick-folder');if(r.folder){$('destination').value=r.folder;invalidatePlan();}}catch(e){$('plan-error').textContent=e.message;}};
$('prepare').onclick=async()=>{try{$('plan-error').textContent='';state.plan=await api('prepare',{scan_id:state.scan.id,selected:[...state.selected],destination:$('destination').value});$('validated').hidden=false;$('validated-text').textContent=state.plan.items.length+' files · '+bytes(state.plan.bytes)+' · plan validated. Contents will be checked again before moving.';$('consent').checked=false;$('execute').disabled=true;}catch(e){invalidatePlan();$('plan-error').textContent=e.message;}};
$('consent').onchange=()=>{$('execute').disabled=!$('consent').checked||!state.plan;};
$('execute').onclick=async()=>{if(!state.plan||!$('consent').checked)return;try{state.busy=true;$('execute').disabled=true;$('prepare').disabled=true;$('destination').disabled=true;$('pick-destination').disabled=true;$('plan-error').textContent='Verifying and moving approved files. Keep Katharo open.';const p=await api('execute',{id:state.plan.id,confirmed:true});$('plan-dialog').close();state.selected.clear();state.scan=null;$('results').hidden=true;notice('Quarantine '+p.status+'. Review individual results below. Total storage is unchanged.');await history();}catch(e){$('plan-error').textContent=e.message;}finally{state.busy=false;$('prepare').disabled=false;$('destination').disabled=false;$('pick-destination').disabled=false;}};
$('close-compare').onclick=()=>$('compare-dialog').close();$('compare-keep').onclick=async()=>{if(state.compare){state.kept.add(state.compare.id);renderGroups();try{await api('decision',{scan_id:state.scan.id,group_id:state.compare.id,decision:'keep-both-distinct-purpose'});}catch(e){notice(e.message);}}$('compare-dialog').close();};
$('history-list').addEventListener('click',async e=>{const b=e.target.closest('[data-restore]');if(!b)return;try{b.disabled=true;b.textContent='Restoring…';const p=await api('restore',{id:b.dataset.restore});notice('Restore outcome: '+p.status+'. Occupied original locations are never overwritten.');await history();}catch(err){notice(err.message);b.disabled=false;b.textContent='Restore available files';}});
$('nav-history').onclick=history;$('refresh-history').onclick=history;$('nav-workspace').onclick=()=>{$('history').hidden=true;$('workspace').hidden=false;$('nav-workspace').classList.add('active');$('nav-history').classList.remove('active');};
(async()=>{try{const response=await fetch('/api/session');state.token=(await response.json()).token;const info=await api('info');$('folder').value=info.default_folder;$('destination').value=info.default_quarantine;}catch(e){notice('Could not connect to the local service: '+e.message);}})();
